name: Linting

on:
  push:
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    name: Lint with golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.19'
          cache: false
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.52
          only-new-issues: true
