name: Unit Tests

on:
  push:
    paths-ignore:
      - README.md

jobs:
  test:
    name: Run unit tests against mocked AWS clients
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - run: go test -v
 